version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: george_ai

  redis:
    image: redis